TRPO_MVC/Models/CategoryModel.cs
namespace TRPO_MVC.Models
{
    public class CategoryModel
    {
        public int ID { get; set; }

        public int? ParentID { get; set; }

        public string Name { get; set; }
    }
}

TRPO_MVC/Models/ElementModel.cs
namespace TRPO_MVC.Models
{
    public class ElementModel
    {
        public int ID { get; set; }

        public string Data { get; set; }

        public Dictionary<string, string> ParsedData { get; set; }
    }
}

TRPO_MVC/Models/ErrorViewModel.cs
namespace TRPO_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TRPO_MVC/Models/FilterDataModel.cs
namespace TRPO_MVC.Models
{
    public class FilterDataModel
    {
        public FilterDataModel(int p, object v)
        {
            predicate = p;
            value = v;
        }

        public int predicate; // -1 lesser, 0 equal, 1 greater

        public object value;
    }
}

TRPO_MVC/Models/Out/CategoryOutModel.cs
using TRPO_DM.Interfaces;

namespace TRPO_MVC.Models.Out
{
    public class CategoryOutModel : ICategoryData
    {
        public int ID { get; set; }

        public int? ParentID { get; set; }

        public string Name { get; set; }
    }
}

TRPO_MVC/Models/Out/ElementOutModel.cs
using TRPO_DM.Interfaces;

namespace TRPO_MVC.Models.Out
{
    public class ElementOutModel : IElementData
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public string Data { get; set; }

        public string ImageURI { get; set; }

        public int CategoryID { get; set; }
    }
}

TRPO_MVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TRPO_MVC.Services;
using TRPO_MVC.Models.Out;

namespace TRPO_MVC.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService;

        public CategoryController(CategoryService service)
        {
            categoryService = service;
        }
        public async Task<IActionResult> List()
        {
            return View(await categoryService.GetAllCategories());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name, int? parid)
        {
            CategoryOutModel categoryData = new CategoryOutModel();

            categoryData.Name = name;
            categoryData.ParentID = parid;

            await categoryService.CreateCategory(categoryData);

            return View("List", await categoryService.GetAllCategories());
        }

        public async Task<IActionResult> Read(int id)
        {
            return View("Read", await categoryService.ReadCategory(id));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            return View("Update", await categoryService.ReadCategory(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, int? parid)
        {
            CategoryOutModel categoryData = new CategoryOutModel();

            categoryData.ID = id;
            categoryData.Name = name;
            categoryData.ParentID = parid;

            await categoryService.UpdateCategory(categoryData);

            return View("List", await categoryService.GetAllCategories());
        }

        [HttpGet]
        public async Task<IActionResult> Delete()
        {
            return View("Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await categoryService.DeleteCategory(id);

            return View("List", await categoryService.GetAllCategories());
        }
    }
}

TRPO_MVC/Controllers/ElementController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TRPO_MVC.Services;
using TRPO_MVC.Models.Out;

namespace TRPO_MVC.Controllers
{
    public class ElementController : Controller
    {
        private ElementService elementService;

        public ElementController(ElementService service)
        {
            elementService = service;
        }
        public async Task<IActionResult> List()
        {
            return View(await elementService.GetAllElements());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name, int catid, string data, string image)
        {
            ElementOutModel elementData = new ElementOutModel();

            if (image == null) image = "";

            elementData.Name = name;
            elementData.CategoryID = catid;
            elementData.Data = data;
            elementData.ImageURI = image;

            await elementService.CreateElement(elementData);

            return View("List", await elementService.GetAllElements());
        }

        public async Task<IActionResult> Read(int id)
        {
            return View("Read", await elementService.ReadElement(id));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            return View("Update", await elementService.ReadElement(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, int catid, string data, string image)
        {
            ElementOutModel elementData = new ElementOutModel();

            if (image == null) image = "";

            elementData.ID = id;
            elementData.Name = name;
            elementData.CategoryID = catid;
            elementData.Data = data;
            elementData.ImageURI = image;

            await elementService.UpdateElement(elementData);

            return View("List", await elementService.GetAllElements());
        }

        [HttpGet]
        public async Task<IActionResult> Delete()
        {
            return View("Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await elementService.DeleteElement(id);

            return View("List", await elementService.GetAllElements());
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            return View("Search");
        }

        [HttpPost]
        public async Task<IActionResult> Search(string? name, int? catid, string? data)
        {
            var searchResult = await elementService.SearchElements(name, catid, data);

            return View("List", searchResult);
        }
    }
}

TRPO_MVC/Views/Category/Create.cshtml
@{
	ViewData["Title"] = "Create Category";
}

<div class="text-center">
    <h1 class="display-4">Create Category</h1>

    <form method="post">
        Name: <input required type="text" name="name" /><br />
        Parent ID: <input required type="number" name="parid" /><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Category/Delete.cshtml
@{
	ViewData["Title"] = "Delete Category";
}

<div class="text-center">
    <h1 class="display-4">Delete Category</h1>

    <form method="post">
        ID: <input required type="number" name="id" /><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Category/List.cshtml
@model List<TRPO_MVC.Models.CategoryModel>
@{
    ViewData["Title"] = "Categories List";
}

<div class="text-center">
    <h1 class="display-4">Categories List</h1>

    @foreach (var cat in this.Model)
    {
        <div>@cat.ID -- @cat.Name: 
            <a asp-area="" asp-controller="Category" asp-action="Read" asp-route-id="@cat.ID">Read</a> 
            <a asp-area="" asp-controller="Category" asp-action="Update" asp-route-id="@cat.ID">Update</a>
        </div>
    }
</div>

TRPO_MVC/Views/Category/Read.cshtml
@model TRPO_MVC.Models.CategoryModel
@{
    ViewData["Title"] = "Read Category";
}

<div class="text-center">
    <h1 class="display-4">Read Category @this.Model.Name</h1>

	ID: @this.Model.ID<br />
	Name: @this.Model.Name<br />
	Parent ID: @this.Model.ParentID<br />
</div>

TRPO_MVC/Views/Category/Update.cshtml
@model TRPO_MVC.Models.CategoryModel
@{
	ViewData["Title"] = "Update Category";
}

<div class="text-center">
    <h1 class="display-4">Update Category</h1>

    <form method="post">
        <input hidden required type="number" name="id" value="@this.Model.ID"/>
        Name: <input required type="text" name="name" value="@this.Model.Name"/><br />
        Parent ID: <input type="number" name="parid" value="@this.Model.ParentID"/><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Element/Create.cshtml
@{
	ViewData["Title"] = "Create Element";
}

<div class="text-center">
    <h1 class="display-4">Create Element</h1>

    <form method="post">
        Name: <input required type="text" name="name" /><br />
        Category ID: <input required type="number" name="catid" /><br />
        Data: <input type="text" name="data" value="{}" /><br />
        Image URI: <input type="text" name="image" /><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Element/Delete.cshtml
@{
	ViewData["Title"] = "Delete Element";
}

<div class="text-center">
    <h1 class="display-4">Delete Element</h1>

    <form method="post">
        ID: <input required type="number" name="id" /><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Element/List.cshtml
@model List<TRPO_MVC.Models.ElementModel>
@{
    ViewData["Title"] = "Elements List";
}

<div class="text-center">
    <h1 class="display-4">Elements List</h1>

    @foreach (var el in this.Model)
    {
        <div>@el.ID -- @el.Name: 
            <a asp-area="" asp-controller="Element" asp-action="Read" asp-route-id="@el.ID">Read</a> 
            <a asp-area="" asp-controller="Element" asp-action="Update" asp-route-id="@el.ID">Update</a>
        </div>
    }
</div>

TRPO_MVC/Views/Element/Read.cshtml
@model TRPO_MVC.Models.ElementModel
@{
    ViewData["Title"] = "Read Element";
}

<div class="text-center">
    <h1 class="display-4">Read Element @this.Model.Name</h1>

	ID: @this.Model.ID<br />
	Name: @this.Model.Name<br />
	Category: @this.Model.Category.ID - @this.Model.Category.Name<br />
	Data: <br />
	@foreach (var d in this.Model.ParsedData)
	{
		<div>@d.Key -- @d.Value</div>
	}
	Image URI: @this.Model.ImageURI<br />
</div>

TRPO_MVC/Views/Element/Search.cshtml
@{
	ViewData["Title"] = "Search Element";
}

<div class="text-center">
    <h1 class="display-4">Search Element</h1>

    <form method="post">
        Name: <input type="text" name="name" /><br />
        Category ID: <input type="number" name="catid" /><br />
        Data: <input type="text" style="width: 90%" name="data" value="" /><br />
        <input type="submit" value="Search" />
    </form>
</div>

TRPO_MVC/Views/Element/Update.cshtml
@model TRPO_MVC.Models.ElementModel
@{
	ViewData["Title"] = "Update Element";
}

<div class="text-center">
    <h1 class="display-4">Update Element</h1>

    <form method="post">
        <input hidden required type="number" name="id" value="@this.Model.ID"/>
        Name: <input required type="text" name="name" value="@this.Model.Name"/><br />
        Category ID: <input required type="number" name="catid" value="@this.Model.Category.ID"/><br />
        Data: <input type="text" name="data" value="@this.Model.Data"/><br />
        Image URI: <input type="text" name="image" value="@this.Model.ImageURI"/><br />
        <input type="submit" value="Submit" />
    </form>
</div>

TRPO_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPO_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TRPO_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-brand">TRPO_MVC</div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Element" asp-action="List">Elements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Element" asp-action="Create">Create Element</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Element" asp-action="Delete">Delete Element</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Element" asp-action="Search">Search Element</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="List">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Create">Create Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Delete">Delete Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TRPO_MVC - <a asp-area="" asp-controller="Element" asp-action="List">Elements again again</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>